[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["jdk21_headless", "maven"]

[build.nixpacksPlan.phases.build]
cmds = ["mvn -B -DskipTests clean package"]

[deploy]
startCommand = "java -jar target/*.jar"